const Data = [
  {
    title: "drill",
    category: "electronics",
    img: "images/drill1.jpg",
    price: "$24",
  },
  {
    title: "refrigerator",
    category: "electronics",
    price: "$320",
    img: "images/frig.webp",
  },
  {
    title: "bulb",
    category: "electronics",
    price: "$42",
    img: "images/bulb.jpeg",
  },
  {
    title: "t-shirt",
    category: "clothes",
    price: "$220",
    img: "images/shirt.jpg",
  },
  {
    title: "jeans",
    category: "clothes",
    price: "$320",
    img: "images/hoddie.jpg",
  },
  {
    title: "hoddlie",
    category: "clothes",
    price: "$210",
    img: "images/hoddie.jpg",
  },
  {
    title: "shoes",
    category: "sports",
    price: "$220",
    img: "images/shoes.jpeg",
  },
  {
    title: "dumble",
    category: "sports",
    img: "images/gym.jpeg",
    price: "$60",
  },
  {
    title: "football",
    category: "sports",
    price: "$200",
    img: "images/ball.jpeg",
  },
  {
    title: "sunglasses",
    category: "sunglasses",
    price: "$10",
    img: "images/sung.jpeg",
  },
  {
    title: "sunglasses",
    category: "sunglasses",
    price: "$10",
    img: "images/sunglasses.jpg",
  },
  {
    title: "sunglasses",
    category: "sunglasses",
    price: "$10",
    img: "images/sunglasses3.jpg",
  },
  {
    title: "Mobile",
    category: "Mobile",
    price: "$320",
    img: "images/mobile1.jpeg",
  },
  {
    title: "Mobile",
    category: "Mobile",
    price: "$320",
    img: "images/mobile2.jpeg",
  },
  {
    title: "Mobile",
    category: "Mobile",
    price: "$320",
    img: "images/mobile3.jpeg",
  },
  {
    title: "Laptop",
    category: "Laptop",
    price: "$220",
    img: "images/leptop1.jpeg",
  },
  {
    title: "Laptop",
    category: "Laptop",
    price: "$220",
    img: "images/leptop2.jpeg",
  },
  {
    title: "Laptop",
    category: "Laptop",
    price: "$220",
    img: "images/leptop3.jpeg",
  },
  {
    title: "Watches",
    category: "Watches",
    price: "$120",
    img: "images/watches.jpeg",
  },
  {
    title: "Watches",
    category: "Watches",
    price: "$120",
    img: "images/watches1.jpeg",
  },
  {
    title: "Watches",
    category: "Watches",
    price: "$120",
    img: "images/watches2.jpeg",
  },
  {
    title: "sent",
    category: "sent",
    price: "$30",
    img: "images/sent.jpeg",
  },
  {
    title: "sent",
    category: "sent",
    price: "$30",
    img: "images/sent3.jpeg",
  },
  {
    title: "sent",
    category: "sent",
    price: "$10",
    img: "images/sent2.jpeg",
  },
  {
    title: "Airpods",
    category: "Airpods",
    price: "$40",
    img: "images/airpods1.jpeg",
  },
  {
    title: "Airpods",
    category: "Airpods",
    price: "$30",
    img: "images/airpods2.jpeg",
  },
  {
    title: "Airpods",
    category: "Airpods",
    price: "$70",
    img: "images/airpods3.jpeg",
  },
];
export default Data;
